name: provider_template
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  path_provider_android: ^2.0.11
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  freezed: ^2.4.2
  integration_test:
    sdk: flutter
  mocktail: ^1.0.1
  injectable_generator: ^2.4.0
  husky: ^0.1.6

flutter:
  uses-material-design: true
